apiVersion: v1
kind: Namespace
metadata:
  name: mydoc-staging
  labels:
    name: mydoc-staging
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: mydoc-production
  labels:
    name: mydoc-production
    environment: production